on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  test_job:
    name: test job
    runs-on: windows-latest
    steps:
      - name: Get started
        run: winget update
